import './globals.css';
import type { Metadata } from 'next';
import { ConfigProvider } from 'antd';

import { Header } from '@/components/common/Header';
import theme from '@/lib/styles/theme';
import Pretendard from '@/lib/styles/font';
import StyledComponentsRegistry from '@/lib/styles/AntdRegistry';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={`${Pretendard.className} bg-slate-0`}>
				<ConfigProvider theme={theme}>
					<StyledComponentsRegistry>
						<Header />
						<div className="my-16">{children}</div>
					</StyledComponentsRegistry>
				</ConfigProvider>
			</body>
		</html>
	);
}
